name: Build ESP32-C3 MicroPython with TWAI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup ESP-IDF
      uses: espressif/setup-esp-idf@v1
      with:
        version: v5.3.1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build cmake python3 python3-pip

    - name: Build mpy-cross
      run: |
        cd micropython/mpy-cross
        mkdir -p build
        cd build
        cmake ..
        ninja

    - name: Build firmware ESP32-C3
      run: |
        cd micropython/ports/esp32
        make submodules
        idf.py -D MICROPY_BOARD=ESP32C3_GENERIC \
               -D USER_C_MODULES="../../../../cmodules/micropython-esp32-twai/src_can_v2/micropython.cmake" \
               -B build_ESP32C3_GENERIC build

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v3
      with:
        name: firmware-esp32c3-twai
        path: micropython/ports/esp32/build_ESP32C3_GENERIC/*.bin
